### ISSUE TITLE
Is the Guncon 3 working?

### ISSUE THREAD

**Issue by kingkweus** [sonik-br/GunconUSB#4]
After installing all required drivers, i cant really get any input to show up. Am I missing something or is it normal?

**Comment by kingkweus** [comment]
Got it to work after getting new sensors. Is there a way to implement deadzone of some kind? mouse movement is kinda jarry.

**Comment by sonik-br** [comment]
Can you explain it better?
It's in mouse mode? Testing on desktop or inside a emulator?

**Comment by kingkweus** [comment]
Yeah its in mouse mode and tested on desktop and emulation. trying to get it to hold still is quite a challenge and it makes it a bit difficult to make some shots.

**Comment by sonik-br** [comment]
Using it's original IR LEDs?

**Comment by kingkweus** [comment]
yeah with the original ir led.

**Comment by sonik-br** [comment]
Sorry but I don't know why it's not working as expected.
There's another version (not made by me). Check it out at https://github.com/sonik-br/GunconUSB/issues/2#issuecomment-1400862670

**Comment by kingkweus** [comment]
I actually got it to start working well so it was probably a problem on my part. thanks for the hard work though, got me to use my guncon 3 which were just collecting dust.

**Comment by Jonathan7299** [comment]
> I actually got it to start working well so it was probably a problem on my part. thanks for the hard work though, got me to use my guncon 3 which were just collecting dust.

How were you able to calibrate it and get it working? The only thing I see on my part is a bunch of Visual Studio Code files.

**Comment by kingkweus** [comment]
> > I actually got it to start working well so it was probably a problem on my part. thanks for the hard work though, got me to use my guncon 3 which were just collecting dust.
> 
> How were you able to calibrate it and get it working? The only thing I see on my part is a bunch of Visual Studio Code files.

you need to compile it in visual studio. heres my precompiled.
https://drive.google.com/file/d/1oCTA3BKA3HpKYL7guSxEaiSJYkS-0lz1/view?usp=sharing
